Q1.Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

Q2.Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [2]:
arr1=np.array([int(input()) for i in range(5)])
arr2=np.array([int(input()) for i in range(5)])
print(np.sort(np.concatenate((arr1,arr2))))

8
5
3
2
6
2
7
6
4
1
[1 2 2 3 4 5 6 6 7 8]


Q3.Write a code snippet to find the dimensions of a ndarray and its size.

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.ndim)
print(arr.size)

1
9


Q4.How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [49]:
arr=np.array([1,2,3,4,5,6])
t=arr
t=t[:, np.newaxis]
print(t)
print(arr)
t=arr
t=np.expand_dims(t,1)
print(t)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Q5.Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [54]:
## Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))
print('vertical Apend:',np.vstack((f,g)))

Horizontal Append: [1 2 3 4 5 6]
vertical Apend: [[1 2 3]
 [4 5 6]]


Q6.How to get unique items and counts of unique items?

In [57]:
#np.unique function can be used to get the unique items. 
#By passing the argument return_counts=True argument along with the array return the unique items and their counts
a=np.arange(1,20)
print(np.unique(a,return_counts=True))

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))
